"""Tests for the email digest module."""

from __future__ import annotations

import asyncio
from unittest.mock import MagicMock, patch

import pytest

from curiopilot.config import EmailConfig
from curiopilot.email_digest import render_briefing_html, send_briefing_email


# ── render_briefing_html ─────────────────────────────────────────────────────


def test_render_briefing_html_contains_html_structure():
    md = "# Hello World\n\nSome **bold** text."
    html = render_briefing_html(md)
    assert "<!DOCTYPE html>" in html
    assert "<h1>" in html
    assert "<strong>bold</strong>" in html
    assert "Generated by CurioPilot" in html


def test_render_briefing_html_tables():
    md = "| A | B |\n|---|---|\n| 1 | 2 |"
    html = render_briefing_html(md)
    assert "<table>" in html
    assert "<td>1</td>" in html


# ── send_briefing_email ──────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_send_skips_when_no_password():
    cfg = EmailConfig(sender_email="test@gmail.com", recipient_email="r@test.com")
    with patch("curiopilot.email_digest.smtplib") as mock_smtp:
        await send_briefing_email(cfg, "# Test", "2026-01-01")
        mock_smtp.SMTP.assert_not_called()


@pytest.mark.asyncio
async def test_send_skips_when_no_sender():
    cfg = EmailConfig(sender_email="", recipient_email="r@test.com")
    with patch("curiopilot.email_digest.smtplib") as mock_smtp:
        await send_briefing_email(cfg, "# Test", "2026-01-01", password_override="pw")
        mock_smtp.SMTP.assert_not_called()


@pytest.mark.asyncio
async def test_send_happy_path():
    cfg = EmailConfig(
        smtp_host="smtp.gmail.com",
        smtp_port=587,
        sender_email="sender@gmail.com",
        recipient_email="recipient@test.com",
    )
    mock_server = MagicMock()
    mock_server.__enter__ = MagicMock(return_value=mock_server)
    mock_server.__exit__ = MagicMock(return_value=False)

    with patch("curiopilot.email_digest.smtplib.SMTP", return_value=mock_server):
        await send_briefing_email(
            cfg, "# Briefing\n\nContent here.", "2026-03-26", password_override="test-pw"
        )

    mock_server.starttls.assert_called_once()
    mock_server.login.assert_called_once_with("sender@gmail.com", "test-pw")
    mock_server.send_message.assert_called_once()

    # Check the email message content
    msg = mock_server.send_message.call_args[0][0]
    assert msg["Subject"] == "CurioPilot Briefing -- 2026-03-26"
    assert msg["From"] == "sender@gmail.com"
    assert msg["To"] == "recipient@test.com"


@pytest.mark.asyncio
async def test_send_password_override_takes_precedence(monkeypatch):
    monkeypatch.setenv("CURIOPILOT_SMTP_PASSWORD", "env-password")
    cfg = EmailConfig(
        sender_email="sender@gmail.com",
        recipient_email="recipient@test.com",
    )
    mock_server = MagicMock()
    mock_server.__enter__ = MagicMock(return_value=mock_server)
    mock_server.__exit__ = MagicMock(return_value=False)

    with patch("curiopilot.email_digest.smtplib.SMTP", return_value=mock_server):
        await send_briefing_email(cfg, "# Test", "2026-01-01", password_override="override-pw")

    mock_server.login.assert_called_once_with("sender@gmail.com", "override-pw")


@pytest.mark.asyncio
async def test_send_uses_env_var(monkeypatch):
    monkeypatch.setenv("CURIOPILOT_SMTP_PASSWORD", "env-password")
    cfg = EmailConfig(
        sender_email="sender@gmail.com",
        recipient_email="recipient@test.com",
    )
    mock_server = MagicMock()
    mock_server.__enter__ = MagicMock(return_value=mock_server)
    mock_server.__exit__ = MagicMock(return_value=False)

    with patch("curiopilot.email_digest.smtplib.SMTP", return_value=mock_server):
        await send_briefing_email(cfg, "# Test", "2026-01-01")

    mock_server.login.assert_called_once_with("sender@gmail.com", "env-password")
