"""Email digest -- send HTML briefing emails via SMTP."""

from __future__ import annotations

import asyncio
import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import markdown

from curiopilot.config import EmailConfig

log = logging.getLogger(__name__)

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 700px; margin: 0 auto; padding: 20px; color: #1a1a2e;
         background: #f8f9fa; }}
  h1 {{ color: #16213e; border-bottom: 2px solid #0f3460; padding-bottom: 8px; }}
  h2 {{ color: #0f3460; margin-top: 24px; }}
  h3 {{ color: #533483; }}
  a {{ color: #0f3460; }}
  hr {{ border: none; border-top: 1px solid #ddd; margin: 20px 0; }}
  blockquote {{ border-left: 3px solid #0f3460; margin-left: 0;
               padding-left: 12px; color: #555; }}
  code {{ background: #e8e8e8; padding: 2px 5px; border-radius: 3px;
          font-size: 0.9em; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
  th {{ background: #f0f0f0; }}
  .footer {{ margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd;
             font-size: 0.85em; color: #888; }}
</style></head><body>
{body_html}
<div class="footer">Generated by CurioPilot</div>
</body></html>
"""


def render_briefing_html(briefing_markdown: str) -> str:
    """Convert briefing markdown to a styled HTML email body."""
    body_html = markdown.markdown(
        briefing_markdown,
        extensions=["tables", "fenced_code"],
    )
    return _HTML_TEMPLATE.format(body_html=body_html)


def _send_smtp(
    *,
    smtp_host: str,
    smtp_port: int,
    sender_email: str,
    password: str,
    recipient_email: str,
    subject: str,
    html_body: str,
) -> None:
    """Send an HTML email via SMTP with STARTTLS (blocking)."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = recipient_email
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
        server.starttls()
        server.login(sender_email, password)
        server.send_message(msg)


async def send_briefing_email(
    email_config: EmailConfig,
    briefing_markdown: str,
    briefing_date: str,
    *,
    password_override: str | None = None,
) -> None:
    """Render and send the briefing email. Runs SMTP in a thread."""
    password = password_override or os.environ.get("CURIOPILOT_SMTP_PASSWORD", "")
    if not password:
        log.warning("No SMTP password available; skipping email send")
        return
    if not email_config.sender_email:
        log.warning("No sender email configured; skipping email send")
        return

    subject = f"CurioPilot Briefing -- {briefing_date}"
    html_body = render_briefing_html(briefing_markdown)

    await asyncio.to_thread(
        _send_smtp,
        smtp_host=email_config.smtp_host,
        smtp_port=email_config.smtp_port,
        sender_email=email_config.sender_email,
        password=password,
        recipient_email=email_config.recipient_email,
        subject=subject,
        html_body=html_body,
    )
    log.info("Briefing email sent to %s", email_config.recipient_email)
